### ISSUE TITLE
conversion to avif

### ISSUE THREAD

**Issue by vincenttschanz** [joedrago/colorist#16]
This is not an issue, just a question. My apologies to abuse this issue tracker.

The [AOMediaCodec wiki claims](https://github.com/AOMediaCodec/av1-avif/wiki) that Colorist is able to generate and convert to Avif images.
However I can't find anything in the doc or in the cookbook about that. 

Trying the follwing command will fail :
```
colorist convert -a src.png dst.avif
** ERROR: Failed to open file for read: dst.avif
** ERROR: Unknown output file format: dst.avif
```

Can Colorist convert to Avif format?

**Comment by joedrago** [comment]
You probably just don't have a recent build. I don't think I have made a
tagged release since adding avif. When you run colorist with no arguments,
is avif in the -f list?

I will make a tagged release today in case you are depending on Appveyor
for your executable. Also, -a isn't a requirement here to make that command
work.

**Comment by joedrago** [comment]
Alright, I've made a new tagged release (v0.0.35). If you are using Homebrew, upgrading to 35 should make it so that you can use avif files. If you're using AppVeyor, the build is still chugging along right now but should finish and work as well.

**Comment by vincenttschanz** [comment]
I was using v0.0.34 installed with Homebrew. Just upgraded to 0.0.35 and it's working.

Thank you very much!

**Comment by joedrago** [comment]
Excellent!

I saw on your site that you do codec comparisons. If you end up playing around with libavif via colorist, I figured I'd mention how colorist's quality level of 0-100 maps:

https://github.com/joedrago/colorist/blob/master/lib/src/format_avif.c#L158

Basically, colorist's quality range of 0-100 maps to AOM's 63-0 range (63 is lowest quality / max quant, 0 is lossless). If you want to test with AOM's range instead, just scale the number on the commandline accordingly.

**Comment by vincenttschanz** [comment]
It's like you are reading my mind ;) Thanks for the info about the quality level. 

Another question, Does libavif currently support 4:4:4 chroma subsampling?  I tried with --yuv 444 but the output seems to be 422.

**Comment by joedrago** [comment]
Yes, my goal is to (eventually) expose most all of what AOM offers for encoding, and it should already support all combinations of YUV format and bit depth. 

Are you sure it isn't writing out YUV444? If I do:

`colorist generate "256x256,#ff0000" --yuv 444 red.avif`

I see it write:

`Writing AVIF [Q:90] [YUV:444]: red.avif`

... and if I read that image back in, I see it come through the decode process as YUV444. I noticed I'm not printing what format I read back in, but I could add that just for convenience. 

Do you have a specific file/cmdline that exhibits this? I'm all for fixing bugs.

**Comment by vincenttschanz** [comment]
Here's my test image, and the result when converting with `--yuv444 -q 100`

![chroma-test](https://user-images.githubusercontent.com/12425634/55797227-2c9fa900-5acc-11e9-93d2-5ecef9bc1045.png)

![chroma-test_avif](https://user-images.githubusercontent.com/12425634/55797226-2c9fa900-5acc-11e9-8f5b-cf3adf43f91a.png)

**Comment by vincenttschanz** [comment]
Well I just judged the result visually. -q 100 in yuv444 should be lossless and look pixel perfect like the source. However there is a visible degradation and it looks like a chroma-subsampling degradation (Luma is perfect).

But maybe it's a AOM encoder bug.

**Comment by joedrago** [comment]
Ah, that is certainly going to be a round-tripping issue in my YUV
conversion impleme tation. If someone uses libavif and directly gives the
library YUV and receives YUV, they should get the behavior you are
expecting.

However, colorist thinks in RGB, so there is conversion on both ends and I
couldn't use libyuv because it doesn't support RGB conversions higher than
8bpc currently, so I'm sure my RGB conversion just needs a little bit of
love.

**Comment by joedrago** [comment]
I just did some basic napkin math on YUV conversion available here:

https://github.com/joedrago/yuv_math/blob/master/yuv_roundtrip.output.txt

It feels like you're pretty much guaranteed to lose 1-2 codepoints worth of accuracy when going from RGB -> YUV -> RGB if you plan to store both RGB and YUV at the same bit depth. 

I don't know if libyuv would have the same results, or if this is a Known Thing (tm), or if there are some known tweaks people do to minimize this, or if I am missing something obvious in my math. It matches my intuition on how this works though, and I'm honestly surprised/happy that the deltas are so low.

**Comment by joedrago** [comment]
Whoa, actually, I just diff'd the source and destination images here, and I think I have a sampling bug! I'll dig in here.

**Comment by joedrago** [comment]
Wow, that ended up being a bad bug. Here's the fix

https://github.com/joedrago/avif/commit/72d1b550638e8cbe3e6a3366a777ac27a562b632

You were right, I was accidentally entering the YUV422 case for YUV444 due to a bad conditional. I've pushed colorist v0.0.38 everywhere which should fix this, and the new delta is significantly better (with a tolerance of 1 codepoint):

![image](https://user-images.githubusercontent.com/332342/55907770-85367b00-5b8c-11e9-9b9f-677edd553231.png)

Thanks for sticking to your guns on this one, that was a fantastic catch!

**Comment by vincenttschanz** [comment]
Nice! I'm glad I could help to find this bug. Thanks for your work, I'll continue my tests with the new build.

Out of curiosity, what are the tools on your last two screenshots?

**Comment by joedrago** [comment]
The first picture is from the Visual Studio debugger, and the second is
Beyond Compare's image comparison tool.
